/******** DO NOT EDIT THIS FILE ********/
#ifndef _PROCS4TESTS_H
#define _PROCS4TESTS_H
#include "../proc.h"

typedef struct test_procs {
    proc_t* pin;
    proc_t* pni;
} test_procs_t;


proc_t* new_init_proc();

proc_t* new_noninit_proc();

proc_t* new_test_proc(pid_t pid);

test_procs_t* new_test_procs();

void delete_test_procs(test_procs_t* tp);

#endif
