/******** DO NOT EDIT THIS FILE ********/
/* 
 * test_mutex_noop.h - structures and function declarations for unit tests
 * of mutex_noop functions.
 * 
 */  
#ifndef _TEST_MUTEX_NOOP_H
#define _TEST_MUTEX_NOOP_H
#define MUNIT_ENABLE_ASSERT_ALIASES
#include "munit/munit.h"

MunitResult test_mutex_new(const MunitParameter params[], void* fixture);
MunitResult test_mutex_new_null(const MunitParameter params[], void* fixture);
MunitResult test_mutex_enter(const MunitParameter params[], void* fixture);
MunitResult test_mutex_enter_null(const MunitParameter params[], void* fixture);
MunitResult test_mutex_leave(const MunitParameter params[], void* fixture);
MunitResult test_mutex_leave_null(const MunitParameter params[], void* fixture);

static MunitTest tests[] = {
    { "/test_mutex_new", test_mutex_new, NULL, NULL,
        MUNIT_TEST_OPTION_NONE, NULL },
    { "/test_mutex_new_null", test_mutex_new_null, NULL, NULL,
        MUNIT_TEST_OPTION_NONE, NULL },
    { "/test_mutex_enter", test_mutex_enter, NULL, NULL,
        MUNIT_TEST_OPTION_NONE, NULL },
    { "/test_mutex_enter_null", test_mutex_enter_null, NULL, NULL, 
        MUNIT_TEST_OPTION_NONE, NULL },
    { "/test_mutex_leave", test_mutex_enter_null, NULL, NULL, 
        MUNIT_TEST_OPTION_NONE, NULL },
    { "/test_mutex_leave_null", test_mutex_enter_null, NULL, NULL, 
        MUNIT_TEST_OPTION_NONE, NULL },
    { NULL, NULL, NULL, NULL, MUNIT_TEST_OPTION_NONE, NULL},
};

static const MunitSuite suite = {
    "/test_mutex_noop", tests, NULL, 1, MUNIT_SUITE_OPTION_NONE 
};    


#endif