/******** DO NOT EDIT THIS FILE ********/
#include <errno.h>
#include "../mutex_lockvar.h"
#include "test_mutex_lockvar.h"
#include "procs4tests.h"

int main(int argc, char** argv) {
    return munit_suite_main(&suite, NULL, argc, argv);
}

static mutex_t* assert_mutex_enter(proc_t* p) {
    mutex_t* m = mutex_new(p);

    mutex_lockvar_t* lock = (mutex_lockvar_t*) m->addr;
    assert_int(*lock, ==, 0);
    
    mutex_enter(m);
    assert_int(*lock, ==, 1);
    
    *lock = 0;
    
    return m;
}

MunitResult test_mutex_new(const MunitParameter params[], void* fixture) {
    test_procs_t* p = new_test_procs();
    
    mutex_t* min = mutex_new(p->pin);
    mutex_t* mni = mutex_new(p->pni);
    
    mutex_lockvar_t* minlock = (mutex_lockvar_t*) min->addr;
    assert_int(*minlock, ==, 0);
    
    mutex_lockvar_t* mnilock = (mutex_lockvar_t*) mni->addr;
    assert_int(*mnilock, ==, 0);
    
    mutex_delete(min);
    mutex_delete(mni);
    
    delete_test_procs(p);
    
    return MUNIT_OK;
}

MunitResult test_mutex_new_null(const MunitParameter params[], void* fixture) {
    errno = 0;
    assert_null(mutex_new(NULL));
    assert_int(errno, ==, EINVAL);
    
    errno = 0;   
        
    return MUNIT_OK;
}    


MunitResult test_mutex_enter(const MunitParameter params[], void* fixture) {
    test_procs_t* p = new_test_procs();
    
    mutex_t* min = assert_mutex_enter(p->pin);
    mutex_t* mni = assert_mutex_enter(p->pni);

    mutex_delete(min);
    mutex_delete(mni);
    
    delete_test_procs(p);

    return MUNIT_OK;
}

MunitResult test_mutex_enter_null(const MunitParameter params[], void* fixture) {
    mutex_enter(NULL); // should just succeed
    
    return MUNIT_OK;
}

MunitResult test_mutex_leave(const MunitParameter params[], void* fixture) {
    test_procs_t* p = new_test_procs();
    
    mutex_t* m = mutex_new(p->pin);
    mutex_lockvar_t* lock = (mutex_lockvar_t*) m->addr;
    assert_int(*lock, ==, 0);
    
    *lock = 1;
    
    mutex_leave(m);

    assert_int(*lock, ==, 0);

    mutex_delete(m);
    
    delete_test_procs(p);

    return MUNIT_OK;
}

MunitResult test_mutex_leave_null(const MunitParameter params[], 
    void* fixture) {
    // should just silently succeed
    mutex_leave(NULL);

    return MUNIT_OK;
}

