/******** DO NOT EDIT THIS FILE ********/
/* 
 * test_mutex_peterson.h - structures and function declarations for unit tests
 * of mutex_peterson functions.
 *
 */  
#ifndef _TEST_MUTEX_PETERSON_H
#define _TEST_MUTEX_PETERSON_H
#define MUNIT_ENABLE_ASSERT_ALIASES
#include "munit/munit.h"

void* test_setup(const MunitParameter params[], void* user_data);
void test_tear_down(void* fixture);

MunitResult test_mutex_new(const MunitParameter params[], void* fixture);
MunitResult test_mutex_new_null(const MunitParameter params[], void* fixture);
MunitResult test_mutex_enter_01(const MunitParameter params[], void* fixture);
MunitResult test_mutex_enter_02(const MunitParameter params[], void* fixture);
MunitResult test_mutex_enter_null(const MunitParameter params[], void* fixture);
MunitResult test_mutex_leave_01(const MunitParameter params[], void* fixture);
MunitResult test_mutex_leave_02(const MunitParameter params[], void* fixture);
MunitResult test_mutex_leave_null(const MunitParameter params[], void* fixture);

MunitResult test_mutex_delete(const MunitParameter params[], 
    void* fixture);

    
static MunitTest tests[] = {
    { "/test_mutex_new", test_mutex_new, test_setup, test_tear_down,
        MUNIT_TEST_OPTION_NONE, NULL },
    { "/test_mutex_new_null", test_mutex_new_null, test_setup, test_tear_down,
        MUNIT_TEST_OPTION_NONE, NULL },
    { "/test_mutex_enter_01", test_mutex_enter_01, test_setup, test_tear_down,
        MUNIT_TEST_OPTION_NONE, NULL },
    { "/test_mutex_enter_02", test_mutex_enter_02, test_setup, test_tear_down,
        MUNIT_TEST_OPTION_NONE, NULL },
    { "/test_mutex_enter_null", test_mutex_enter_null, test_setup,
        test_tear_down, MUNIT_TEST_OPTION_NONE, NULL },
    { "/test_mutex_leave_01", test_mutex_leave_01, test_setup, test_tear_down,
        MUNIT_TEST_OPTION_NONE, NULL },
    { "/test_mutex_leave_02", test_mutex_leave_02, test_setup, test_tear_down,
        MUNIT_TEST_OPTION_NONE, NULL },
    { "/test_mutex_leave_null", test_mutex_leave_null, test_setup,
        test_tear_down, MUNIT_TEST_OPTION_NONE, NULL },
    { "/test_mutex_delete", test_mutex_delete, test_setup, test_tear_down,
        MUNIT_TEST_OPTION_NONE, NULL },
   { NULL, NULL, NULL, NULL, MUNIT_TEST_OPTION_NONE, NULL},
};

static const MunitSuite suite = {
    "/test_mutex_peterson", tests, NULL, 1, MUNIT_SUITE_OPTION_NONE 
};    


#endif