/******** DO NOT EDIT THIS FILE ********/
#include "test_jobqueue_common.h"
#include "test_pri_jobqueue.h"
#include "../pri_jobqueue.h"

int main(int argc, char** argv) {
    return munit_suite_main(&suite, NULL, argc, argv);
}

void* test_setup(const MunitParameter params[], void* user_data) {
    test_jq_t* test_jq = (test_jq_t*) malloc(sizeof(test_jq_t));
    
    pri_jobqueue_t* q = (pri_jobqueue_t*) malloc(sizeof(pri_jobqueue_t));
    
    q->buf_size = JOB_BUFFER_SIZE;
    q->size = 0;
    
    for (int i = 0; i < q->buf_size; i++) {
        init_job(&q->jobs[i]);
    }
    
    test_jq->q = q;
    test_jq->qimpl = q; 

    // assert valid queue (tests jobqueue_init as side effect)
    assert_queue_initialised(test_jq->qimpl);
    
    test_jq->dequeue = (job_t* (*)(void*, job_t*)) pri_jobqueue_dequeue;
    test_jq->enqueue = (void (*)(void*, job_t*)) pri_jobqueue_enqueue;
    test_jq->is_empty = (bool (*)(void*)) pri_jobqueue_is_empty;
    test_jq->is_full = (bool (*)(void*)) pri_jobqueue_is_full;
    test_jq->peek = (job_t* (*)(void*, job_t*)) pri_jobqueue_peek;
    test_jq->size = (int (*)(void*)) pri_jobqueue_size;
    test_jq->space = (int (*)(void*)) pri_jobqueue_space;

    return test_jq;
}

void test_tear_down(void* fixture) {
    test_jq_t* test_jq = (test_jq_t*) fixture;
    free(test_jq->q);
    
    free(test_jq);
}

MunitResult test_pri_jobqueue_new(const MunitParameter params[], 
    void* fixture) {
    pri_jobqueue_t* q = pri_jobqueue_new();
    
    assert_not_null(q);
    assert_queue_initialised(q);
    
    free(q);
    
    return MUNIT_OK;
}

MunitResult test_pri_jobqueue_init(const MunitParameter params[], 
    void* fixture) {
    return test_pjq_init((test_jq_t*) fixture);
}

MunitResult test_prijq_ndequeue_randpri(const MunitParameter params[], 
    void* fixture) {
    return test_jq_ndequeue_randpri((test_jq_t*) fixture);
}

MunitResult test_prijq_ndequeue_decpri(const MunitParameter params[], 
    void* fixture) {
    return test_jq_ndequeue_decpri((test_jq_t*) fixture);
}

MunitResult test_prijq_ndequeue_incpri(const MunitParameter params[], 
    void* fixture) {
    return test_jq_ndequeue_incpri((test_jq_t*) fixture);
}

MunitResult test_prijq_ndequeue_inout(const MunitParameter params[], 
    void* fixture) {
    return test_jq_ndequeue_inout((test_jq_t*) fixture);
}

MunitResult test_prijq_ndequeue_randinout(const MunitParameter params[], 
    void* fixture) {
    return test_jq_ndequeue_randinout((test_jq_t*) fixture);
}

MunitResult test_prijq_ndequeue_heap(const MunitParameter params[], 
    void* fixture) {
    return test_jq_ndequeue_heap((test_jq_t*) fixture);
}

MunitResult test_prijq_ndequeue_samepid(const MunitParameter params[], 
    void* fixture) {
    return test_jq_ndequeue_samepid((test_jq_t*) fixture);
}

MunitResult test_prijq_ndequeue_sameid(const MunitParameter params[], 
    void* fixture) {
    return test_jq_ndequeue_sameid((test_jq_t*) fixture);
}

MunitResult test_prijq_ndequeue_samepri(const MunitParameter params[], 
    void* fixture) {
    return test_jq_ndequeue_samepri((test_jq_t*) fixture);
}

MunitResult test_prijq_ndequeue_samepidid(const MunitParameter params[], 
    void* fixture) {
    return test_jq_ndequeue_samepidid((test_jq_t*) fixture);
}

MunitResult test_prijq_ndequeue_samepidpri(const MunitParameter params[], 
    void* fixture) {
    return test_jq_ndequeue_samepidpri((test_jq_t*) fixture);
}

MunitResult test_prijq_ndequeue_sameidpri(const MunitParameter params[], 
    void* fixture) {
    return test_jq_ndequeue_sameidpri((test_jq_t*) fixture);
}

MunitResult test_prijq_ndequeue_sameall(const MunitParameter params[], 
    void* fixture) {
    return test_jq_ndequeue_sameall((test_jq_t*) fixture);
}

MunitResult test_prijq_ndequeue_fifo(const MunitParameter params[], 
    void* fixture) {
    return test_jq_ndequeue_fifo((test_jq_t*) fixture);
}

MunitResult test_prijq_dequeue_empty(const MunitParameter params[], 
    void* fixture) {
    return test_jq_dequeue_empty((test_jq_t*) fixture);
}

MunitResult test_prijq_dequeue_null(const MunitParameter params[], 
    void* fixture) {
    return test_jq_dequeue_null((test_jq_t*) fixture);
}

MunitResult test_prijq_enqueue_full(const MunitParameter params[], 
    void* fixture) {
    return test_jq_enqueue_full((test_jq_t*) fixture);
}

MunitResult test_prijq_enqueue_null(const MunitParameter params[], 
    void* fixture) {
    return test_jq_enqueue_null((test_jq_t*) fixture);
}

MunitResult test_prijq_enqueue_zeropri(const MunitParameter params[], 
    void* fixture) {
    return test_jq_enqueue_zeropri((test_jq_t*) fixture);
}

MunitResult test_prijq_enqueue_badjob(const MunitParameter params[], 
    void* fixture) {
    return test_jq_enqueue_badjob((test_jq_t*) fixture);
}

MunitResult test_prijq_is_empty(const MunitParameter params[], void* fixture) {
    return test_jq_is_empty((test_jq_t*) fixture);
}

MunitResult test_prijq_is_empty_notempty(const MunitParameter params[], 
    void* fixture) {
    return test_jq_is_empty_notempty((test_jq_t*) fixture);
}

MunitResult test_prijq_is_empty_nqnotempty(const MunitParameter params[], 
    void* fixture) {
    return test_jq_is_empty_nqnotempty((test_jq_t*) fixture);
}

MunitResult test_prijq_is_empty_null(const MunitParameter params[], 
    void* fixture) {
    return test_jq_is_empty_null((test_jq_t*) fixture);
}

MunitResult test_prijq_is_full_empty(const MunitParameter params[], 
    void* fixture) {
    return test_jq_is_full_empty((test_jq_t*) fixture);
}

MunitResult test_prijq_is_full_filling(const MunitParameter params[], 
    void* fixture) {
    return test_jq_is_full_filling((test_jq_t*) fixture);
}

MunitResult test_prijq_is_full_nqfilling(const MunitParameter params[], 
    void* fixture) {
    return test_jq_is_full_nqfilling((test_jq_t*) fixture);
}

MunitResult test_prijq_is_full_null(const MunitParameter params[], 
    void* fixture) {
    return test_jq_is_full_null((test_jq_t*) fixture);
}

MunitResult test_prijq_peek_full(const MunitParameter params[], void* fixture) {
    return test_jq_peek_full((test_jq_t*) fixture);
}

MunitResult test_prijq_peek_empty(const MunitParameter params[], 
    void* fixture) {
    return test_jq_peek_empty((test_jq_t*) fixture);
}

MunitResult test_prijq_peek_heap(const MunitParameter params[], void* fixture) {
    return test_jq_peek_heap((test_jq_t*) fixture);
}

MunitResult test_prijq_peek_null(const MunitParameter params[], void* fixture) {
    return test_jq_peek_null((test_jq_t*) fixture);
}

MunitResult test_prijq_size_empty(const MunitParameter params[], 
    void* fixture) {
    return test_jq_size_empty((test_jq_t*) fixture);
}

MunitResult test_prijq_size_filling(const MunitParameter params[], 
    void* fixture) {
    return test_jq_size_filling((test_jq_t*) fixture);
}

MunitResult test_prijq_size_nqfilling(const MunitParameter params[], 
    void* fixture) {
    return test_jq_size_nqfilling((test_jq_t*) fixture);
}

MunitResult test_prijq_size_null(const MunitParameter params[], 
    void* fixture) {
    return test_jq_size_null((test_jq_t*) fixture);
}

MunitResult test_prijq_space_empty(const MunitParameter params[], 
    void* fixture) {
    return test_jq_space_empty((test_jq_t*) fixture);
}

MunitResult test_prijq_space_filling(const MunitParameter params[], 
    void* fixture) {
    return test_jq_space_filling((test_jq_t*) fixture);
}

MunitResult test_prijq_space_nqfilling(const MunitParameter params[], 
    void* fixture) {
    return test_jq_space_nqfilling((test_jq_t*) fixture);
}

MunitResult test_prijq_space_null(const MunitParameter params[], 
    void* fixture) {
    return test_jq_space_null((test_jq_t*) fixture);
}

MunitResult test_pri_jobqueue_delete(const MunitParameter params[], 
    void* fixture) {
    pri_jobqueue_t* q = (pri_jobqueue_t*) malloc(sizeof(pri_jobqueue_t));

    /* the following should just not cause errors */
    pri_jobqueue_delete(q);
        
    /* check NULL OK */    
    pri_jobqueue_delete(NULL);
    
    return MUNIT_OK;
}


