/******** DO NOT EDIT THIS FILE ********/
#include <errno.h>
#include "../mutex_noop.h"
#include "test_mutex_noop.h"
#include "procs4tests.h"

int main(int argc, char** argv) {
    return munit_suite_main(&suite, NULL, argc, argv);
}

MunitResult test_mutex_new(const MunitParameter params[], void* fixture) {
    test_procs_t* p = new_test_procs();
    
    mutex_t* m = mutex_new(p->pin);
    
    assert_not_null(m);
    
    mutex_delete(m);
        
    return MUNIT_OK;
}

MunitResult test_mutex_new_null(const MunitParameter params[], void* fixture) {
    errno = 0;
    assert_null(mutex_new(NULL));
    assert_int(errno, ==, EINVAL);
    
    errno = 0;   
        
    return MUNIT_OK;
}    


MunitResult test_mutex_enter(const MunitParameter params[], void* fixture) {
    test_procs_t* p = new_test_procs();
    
    mutex_t* m = mutex_new(p->pin);
    
    mutex_enter(m); // should just succeed

    mutex_delete(m);
    
    delete_test_procs(p);

    return MUNIT_OK;
}

MunitResult test_mutex_enter_null(const MunitParameter params[], void* fixture) {
    mutex_enter(NULL); // should just succeed
    
    return MUNIT_OK;
}

MunitResult test_mutex_leave(const MunitParameter params[], void* fixture) {
    test_procs_t* p = new_test_procs();
    
    mutex_t* m = mutex_new(p->pin);
    
    mutex_leave(m); // should just succeed

    mutex_delete(m);
    
    delete_test_procs(p);

    return MUNIT_OK;
}

MunitResult test_mutex_leave_null(const MunitParameter params[], 
    void* fixture) {
    // should just silently succeed
    mutex_leave(NULL);

    return MUNIT_OK;
}

