/******** DO NOT EDIT THIS FILE ********/
#include <unistd.h>
#include <sys/wait.h>
#include <stdio.h>
#include <errno.h>
#include <sys/mman.h>
#include "test_jobqueue_common.h"
#include "test_sem_jobqueue.h"
#include "../sim_config.h"
#include "../shobject_name.h"
#include "../sem_jobqueue.h"
#include "procs4tests.h"

int main(int argc, char** argv) {
    return munit_suite_main(&suite, NULL, argc, argv);
}

void* test_setup(const MunitParameter params[], void* user_data) {
    test_jq_t* test_jq = (test_jq_t*) malloc(sizeof(test_jq_t));
    
    sem_jobqueue_t* q = sem_jobqueue_new(new_init_proc());
    
    test_jq->q = q;
    test_jq->qimpl = (pri_jobqueue_t*) q->ijq->addr;

    // assert valid queue
    assert_queue_initialised(test_jq->qimpl);
    
    test_jq->dequeue = (job_t* (*)(void*, job_t*)) sem_jobqueue_dequeue;
    test_jq->enqueue = (void (*)(void*, job_t*)) sem_jobqueue_enqueue;
    test_jq->is_empty = (bool (*)(void*)) sem_jobqueue_is_empty;
    test_jq->is_full = (bool (*)(void*)) sem_jobqueue_is_full;
    test_jq->peek = (job_t* (*)(void*, job_t*)) sem_jobqueue_peek;
    test_jq->size = (int (*)(void*)) sem_jobqueue_size;
    test_jq->space = (int (*)(void*)) sem_jobqueue_space;

    errno = 0;
    
    return test_jq;
}

static void del_sem(sem_t* sem, const char* lab) {
    char name[MAX_NAME_SIZE];
    sem_close(sem);
    shobject_name(lab, name);
    sem_unlink(name);
}

static void del_sjq(sem_jobqueue_t* q) {
    del_sem(q->mutex, "sjq.mutex");
    del_sem(q->full, "sjq.full");
    del_sem(q->empty, "sjq.empty");

    ipc_delete(q->ijq);
    free(q);
}

void test_tear_down(void* fixture) {
    test_jq_t* test_jq = (test_jq_t*) fixture;
    sem_jobqueue_t* q = (sem_jobqueue_t*) test_jq->q;
   
    proc_t* p = q->ijq->proc;
    del_sjq(q);    
    proc_delete(p);
    free(test_jq);
}

static MunitResult test_no_semfailure(MunitResult result) {
    if (result == MUNIT_OK)
        assert_int(errno, ==, 0);
    
    return result;
}

MunitResult test_semjq_dequeue_null(const MunitParameter params[], 
    void* fixture) {
    return test_no_semfailure(test_jq_dequeue_null((test_jq_t*) fixture));
}

MunitResult test_semjq_enqueue_null(const MunitParameter params[], 
    void* fixture) {
    return test_no_semfailure(test_jq_enqueue_null((test_jq_t*) fixture));
}

MunitResult test_semjq_is_empty_null(const MunitParameter params[], 
    void* fixture) {
    return test_no_semfailure(test_jq_is_empty_null((test_jq_t*) fixture));
}

MunitResult test_semjq_is_full_null(const MunitParameter params[], 
    void* fixture) {
    return test_no_semfailure(test_jq_is_full_null((test_jq_t*) fixture));
}

MunitResult test_semjq_peek_null(const MunitParameter params[], 
    void* fixture) {
    return test_no_semfailure(test_jq_peek_null((test_jq_t*) fixture));
}

MunitResult test_semjq_size_null(const MunitParameter params[], 
    void* fixture) {
    return test_no_semfailure(test_jq_size_null((test_jq_t*) fixture));
}

MunitResult test_semjq_space_null(const MunitParameter params[], 
    void* fixture) {
    return test_no_semfailure(test_jq_space_null((test_jq_t*) fixture));
}

MunitResult test_sem_jobqueue_2proc_ndequeue(
    const MunitParameter params[], void* fixture) {
    pid_t pid = fork();
    
    if (pid < -1)
        return MUNIT_FAIL;
    
    if (pid == 0) {
        // in child
        proc_t* cp = new_init_proc();
        sem_jobqueue_t* sjq = sem_jobqueue_new(cp);

        assert_not_null(sjq);
        
        for (int i = 0; i < JOB_BUFFER_SIZE * 2; i++) {
            job_t expj;
            set_job(&expj, i + 1, i, i + 1);
            job_t dqj;

            errno = 0;
            sem_jobqueue_dequeue(sjq, &dqj);
            assert_true(equal_jobs(&dqj, &expj));
            assert_int(errno, ==, 0);
        }
        
        
        del_sjq(sjq);
        proc_delete(cp);
        
        exit(EXIT_SUCCESS);
    } else {
        // in parent
        int child_stat;

        proc_t* pp = new_noninit_proc();
        sem_jobqueue_t* sjq = sem_jobqueue_new(pp);

        assert_not_null(sjq);

        for (int i = 0; i < JOB_BUFFER_SIZE * 2; i++) {
            job_t j;
            set_job(&j, i + 1, i, i + 1);
            errno = 0;
            sem_jobqueue_enqueue(sjq, &j);
            assert_int(errno, ==, 0);
        } 
        
        waitpid(pid, &child_stat, 0);
        assert_false(sem_jobqueue_is_full(sjq));
        assert_true(sem_jobqueue_is_empty(sjq));
        
        del_sjq(sjq);
        proc_delete(pp);
        assert_int(WEXITSTATUS(child_stat), ==, EXIT_SUCCESS);
    }

    return MUNIT_OK;
}

MunitResult test_sem_jobqueue_delete(const MunitParameter params[], 
    void* fixture) {
    proc_t* proc = new_init_proc();
    sem_jobqueue_t* q = sem_jobqueue_new(proc);   
    char* qname = q->ijq->name;
    /* the following should just not cause errors */
    sem_jobqueue_delete(q);
    
    /* make sure that unlink shared memory in case sem_jobqueue_delete 
     * doesn't 
     */
    char sname[MAX_NAME_SIZE];
    shobject_name("sjq.mutex", sname);
    sem_unlink(sname);
    shobject_name("sjq.full", sname);
    sem_unlink(sname);
    shobject_name("sjq.empty", sname);
    sem_unlink(sname);
    
    shm_unlink(qname);
    free(proc);

    /* check NULL OK */    
    sem_jobqueue_delete(NULL);

    return MUNIT_OK;
}

