/******** DO NOT EDIT THIS FILE ********/
/* 
 * test_shobject_name.h - structures and function declarations for unit tests
 * of the shobject_name function.
 * 
 */  
#ifndef _TEST_SHOBJECT_NAME_H
#define _TEST_SHOBJECT_NAME_H
#define MUNIT_ENABLE_ASSERT_ALIASES
#include "munit/munit.h"

MunitResult test_shobject_name_short(const MunitParameter params[],
    void* fixture);
MunitResult test_shobject_name_empty(const MunitParameter params[],
    void* fixture);
MunitResult test_shobject_name_char(const MunitParameter params[],
    void* fixture);
MunitResult test_shobject_name_long(const MunitParameter params[],
    void* fixture);
MunitResult test_shobject_name_null(const MunitParameter params[],
    void* fixture);
    
MunitResult test_shobject_name_short_heap(const MunitParameter params[],
    void* fixture);
MunitResult test_shobject_name_empty_heap(const MunitParameter params[],
    void* fixture);
MunitResult test_shobject_name_char_heap(const MunitParameter params[],
    void* fixture);
MunitResult test_shobject_name_long_heap(const MunitParameter params[],
    void* fixture);
MunitResult test_shobject_name_null_heap(const MunitParameter params[],
    void* fixture);

static MunitTest tests[] = {
    { "/test_shobject_name_short", test_shobject_name_short, NULL, NULL,
        MUNIT_TEST_OPTION_NONE, NULL },
    { "/test_shobject_name_empty", test_shobject_name_empty, NULL, NULL,
        MUNIT_TEST_OPTION_NONE, NULL },
    { "/test_shobject_name_char", test_shobject_name_char, NULL, NULL,
        MUNIT_TEST_OPTION_NONE, NULL },
    { "/test_shobject_name_long", test_shobject_name_long, NULL, NULL,
        MUNIT_TEST_OPTION_NONE, NULL },
    { "/test_shobject_name_null", test_shobject_name_null, NULL, NULL,
        MUNIT_TEST_OPTION_NONE, NULL },

    { "/test_shobject_name_short_heap", test_shobject_name_short_heap, NULL,
        NULL, MUNIT_TEST_OPTION_NONE, NULL },
    { "/test_shobject_name_empty_heap", test_shobject_name_empty_heap, NULL,
        NULL, MUNIT_TEST_OPTION_NONE, NULL },
    { "/test_shobject_name_char_heap", test_shobject_name_char_heap, NULL, NULL,
        MUNIT_TEST_OPTION_NONE, NULL },
    { "/test_shobject_name_long_heap", test_shobject_name_long_heap, NULL, NULL,
        MUNIT_TEST_OPTION_NONE, NULL },
    { "/test_shobject_name_null_heap", test_shobject_name_null_heap, NULL, NULL,
        MUNIT_TEST_OPTION_NONE, NULL },
    { NULL, NULL, NULL, NULL, MUNIT_TEST_OPTION_NONE, NULL},
};

const MunitSuite suite = {
    "/test_shobject_name", tests, NULL, 1, MUNIT_SUITE_OPTION_NONE 
};    


#endif