/******** DO NOT EDIT THIS FILE ********/
/* This is the busy waiting consumer application/simulation 
 * Type:
 *      ./bin/bwait_consumer_<mutex_type> 
 * for usage, where <mutex_type> is replaced by either noop or peterson, e.g.:
 *      ./bin/bwait_consumer_noop
 * gives a usage message.
 *
 * The source code for the usage message is in print_usage in sim_control.c.
 */
#include "sim_control.h"
#include "ipc_jobqueue.h"
#include "mutex.h"

int main(int argc, char** argv) {
    shobj_ctrl_t queue_ctrl = { (sh_constructor_t) ipc_jobqueue_new, 
        (sh_destructor_t) ipc_jobqueue_delete };
    shobj_ctrl_t mutex_ctrl = { (sh_constructor_t) mutex_new, 
        (sh_destructor_t) mutex_delete };
    
    simulation_t* sim = simulation_setup(argc, argv, BWAIT_CONS_PROC, 
        &queue_ctrl, &mutex_ctrl);

    proc_t* proc = sim->proc;

    while (proc->jobs) {
        job_t job;
        job.id = 0;
        job_t* job_dq = NULL;

        mutex_enter(sim->mutex);
        
        if (!ipc_jobqueue_is_empty(sim->queue))
            job_dq = ipc_jobqueue_dequeue(sim->queue, &job);

        mutex_leave(sim->mutex);
        
        simulation_update(sim, job_dq);  // logs to the consumer joblog
                
        if (sim->skips >= sim->skip_limit)
            break;
    }
    
    return simulation_teardown(sim);    
}
