/******** DO NOT EDIT THIS FILE ********/
/* This is the busy waiting producer application/simulation 
 * Type:
 *      ./bin/bwait_producer_<mutex_type> 
 * for usage, where <mutex_type> is replaced by either noop or peterson, e.g.:
 *      ./bin/bwait_producer_noop
 * gives a usage message.
 *
 * The source code for the usage message is in print_usage in sim_control.c.
 */
#include "sim_control.h"
#include "ipc_jobqueue.h"
#include "mutex.h"

/* TODO: think about what I want to do about priority handling */

int main(int argc, char** argv) {
    shobj_ctrl_t queue_ctrl = { (sh_constructor_t) ipc_jobqueue_new, 
        (sh_destructor_t) ipc_jobqueue_delete };
    shobj_ctrl_t mutex_ctrl = { (sh_constructor_t) mutex_new, 
        (sh_destructor_t) mutex_delete };

    simulation_t* sim = simulation_setup(argc, argv, BWAIT_PROD_PROC, 
        &queue_ctrl, &mutex_ctrl);
        
    proc_t* proc = sim->proc;
    
    unsigned int id = 1;
    
    while (proc->jobs) {
        job_t job;
        
        job_set(&job, proc->id, id, 1 + id % 3, 
            id % 2 ? "bwodd_label" : "bweven_label");

        mutex_enter(sim->mutex);
        
        if (!ipc_jobqueue_is_full(sim->queue)) {
            ipc_jobqueue_enqueue(sim->queue, &job);
            
            id++;
        }
        
        mutex_leave(sim->mutex);
        
        simulation_update(sim, id > job.id ? &job : NULL);  
            // logs to the producer joblog

        if (sim->skips >= sim->skip_limit)
            break;
        
    }
    
    return simulation_teardown(sim);
}
