/******** DO NOT EDIT THIS FILE ********/

#include <stdlib.h>
#include <sys/mman.h>
#include <sys/stat.h>        /* For mode constants */
#include <fcntl.h>           /* For O_* constants */
#include <unistd.h>
#include <string.h>
#include <errno.h>
#include "ipc.h"
#include "shobject_name.h"

#define NON_INIT_DELAY  1000

ipc_t* ipc_new(proc_t* proc, const char* label, size_t size) {
    if (!proc || !size) {
        errno = EINVAL;
        return NULL;
    }
        
    ipc_t* ipc = (ipc_t*) malloc(sizeof(ipc_t));
    
    if (!ipc)
        return NULL;
        
    ipc->proc = proc;

    shobject_name(label, ipc->name);
    
    int oflag = O_RDWR;
    int prot = PROT_READ | PROT_WRITE;
    
    if (proc->is_init) {
        oflag |= O_CREAT;
        shm_unlink(ipc->name);
    } else {
        delay_ms(NON_INIT_DELAY); 
            // delay non-init processes here to allow init to complete set up
    }
 
    bool success = false;
    int fd = shm_open(ipc->name, oflag, S_IRUSR | S_IWUSR);
        
    if (fd != -1) {
        if (proc->is_init) ftruncate(fd, size);
        
        ipc->addr = mmap(NULL, size, prot, MAP_SHARED, fd, 0L);
        
        success = ipc->addr != MAP_FAILED;    
           
        close(fd);
    }    
    
    if (!success) {
        free(ipc);
        return NULL;
    }
        
    if (proc->is_init) memset(ipc->addr, 0, size);
        
    return ipc;
}

void ipc_delete(ipc_t* ipc) {
    if (ipc) {
        shm_unlink(ipc->name);
        
        free(ipc);
    }
}
