#******** DO NOT EDIT THIS FILE ********#
# this is the main make build file project

include make.cfg

rmsho := rmsho
runrmsho := run$(rmsho)

# top-level targets
all: $(runrmsho) all_apps tests
.PHONY: all

all_apps: bwait_apps sem_apps
.PHONY: all_apps

bwait_apps: use_alt $(bwait_app_sources:%=%_apps)
.PHONY: bwait_apps

bwait_consumer_apps: $(mutex_types:%=$(bin)/bwait_consumer_%)
.PHONY: bwait_consumer_apps

bwait_producer_apps: $(mutex_types:%=$(bin)/bwait_producer_%)
.PHONY: bwait_producer_apps

sem_apps: use_alt $(sem_app_sources:%=$(bin)/%)
.PHONY: sem_apps

tests: use_alt $(test_sources:%=$(testbin)/%)
.PHONY: tests

$(runrmsho): clean_$(rmsho) $(rmsho)
	./$(runrmsho).sh
.PHONY: $(runrmsho)

use_alt:
ifdef alt_job
	cp alt/job_$(alt_job).c ./job.c
endif
ifdef alt_queue
	cp alt/pri_jobqueue_$(alt_queue).c ./pri_jobqueue.c
endif
.PHONY: use_alt

depend:
	@make -f $(make_depend)
	
marktest: clean_marktest
	-@mkdir -p ./solution
	$(foreach f, $(submission_sources), cp ./$f.c ./solution;)
	-@mkdir -p ./tmpmark
	$(foreach f, $(submission_sources), cp ./$f.c ./tmpmark;)
.PHONY: marktest

$(submission): clean_$(submission)
	-@mkdir -p ./$@/$(assignment)-submit
	$(foreach f, $(submission_sources), cp ./$f.c ./$@/$(assignment)-submit;)
	cd ./$@; \
	    zip -r -q ./$(assignment)-submit.zip ./$(assignment)-submit

clean: clean_$(bin) clean_core clean_$(objects) clean_submission clean_out \
    clean_marktest
.PHONY: clean

clean_all: clean clean_depend clean_dist clean_$(rmsho)
.PHONY: clean_all

-include $(depend_sources:%=./$(depend)/%.d)
-include $(testdepend_sources:%=./$(testdepend)/%.d)

# application targets
$(rmsho): $(rmsho).c $(objects)/shobject_name.o
	$(CC) $(CFLAGS) $^ -o $@ $(LDFLAGS) $(LDFLAGS_SEM)

bin/bwait_consumer_%: $(objects)/bwait_consumer.o $(app_libs) \
    $(objects)/mutex_%.o | $(bin)
	$(CC) $(CFLAGS) $^ -o $@ $(LDFLAGS)

bin/bwait_producer_%: $(objects)/bwait_producer.o $(app_libs) \
    $(objects)/mutex_%.o | $(bin)
	$(CC) $(CFLAGS) $^ -o $@ $(LDFLAGS)

bin/sem_%: $(objects)/sem_%.o $(sem_app_libs) | $(bin)
	$(CC) $(CFLAGS) $^ -o $@ $(LDFLAGS)  $(LDFLAGS_SEM)

# test targets
$(testbin)/test_ipc: $(testobjects)/test_ipc.o $(test_ipc_libs) | $(testbin)
	$(CC) $(CFLAGS) $^ -o $@ $(LDFLAGS)

$(testbin)/test_joblog: $(testobjects)/test_joblog.o \
    $(job_lib) $(joblog_lib) $(munit_lib) $(procs4tests_lib) $(proc_lib) \
    | $(testbin)
	$(CC) $(CFLAGS) $^ -o $@

$(testbin)/test_pri_jobqueue: $(testobjects)/test_pri_jobqueue.o $(job_lib) \
    $(objects)/pri_jobqueue.o $(munit_lib) $(test_jobqueue_common_lib) \
    | $(testbin)
	$(CC) $(CFLAGS) $^ -o $@

$(testbin)/test_ipc_jobqueue: $(testobjects)/test_ipc_jobqueue.o \
    $(queue_libs) $(test_ipc_libs) $(test_jobqueue_common_lib) \
    $(job_lib) | $(testbin)
	$(CC) $(CFLAGS) $^ -o $@ $(LDFLAGS)

$(testbin)/test_sem_jobqueue: $(testobjects)/test_sem_jobqueue.o \
    $(sem_queue_libs) $(test_ipc_libs)  $(test_jobqueue_common_lib) \
    $(job_lib) | $(testbin)
	$(CC) $(CFLAGS) $^ -o $@ $(LDFLAGS) $(LDFLAGS_SEM)

$(testbin)/test_sim_control: $(testobjects)/test_sim_control.o \
    $(objects)/sim_control.o $(munit_lib) $(proc_lib) $(joblog_lib) | $(testbin)
	$(CC) $(CFLAGS) $^ -o $@ $(LDFLAGS)

$(testbin)/test_mutex_%: $(testobjects)/test_mutex_%.o $(objects)/mutex_%.o \
    $(test_ipc_libs) | $(testbin)
	$(CC) $(CFLAGS) $^ -o $@ $(LDFLAGS)
    
$(testbin)/test_%: $(testobjects)/test_%.o $(objects)/%.o $(munit_lib) \
    $(proc_lib) | $(testbin)
	$(CC) $(CFLAGS) $^ -o $@

# all object targets
all_objects: $(sources:%=$(objects)/%.o)
.PHONY: all_objects

all_testobjects: $(tests:%=$(testobjects)/%.o)
.PHONY: all_testobjects

# clean sub-targets
clean_$(bin):
	-rm -f ./a.out
	-rm -rf ./$(testbin)
	-rm -rf ./$(bin)
.PHONY: clean_$(bin)
	
clean_core:
	-rm -f ./core.*
	-rm -f ./$(bin)/core.*
	-rm -f ./$(testbin)/core.*
.PHONY: clean_core
    
clean_$(objects):
	-rm -f ./*.o
	-rm -rf ./$(testobjects)
	-rm -rf ./$(objects)
.PHONY: clean_obj

clean_out:
	-rm -rf ./out
.PHONY: clean_out

clean_$(dist):
	-rm -rf ./$(dist)
.PHONY: clean_$(dist)

clean_$(depend):
	@make -f $(make_depend) clean
.PHONY: clean_$(depend)

clean_$(rmsho):
	-rm -rf ./$(rmsho)
.PHONY: clean_$(rmsho)

clean_$(submission):
	-rm -rf ./$(submission)
.PHONY: clean_$(submission)

clean_marktest:
	-rm -rf ./solution
	-rm -rf ./tmpmark
.PHONY: clean_marktest

# make directory sub-targets
$(bin): ; -@mkdir -p ./$@

$(testbin): ; -@mkdir -p ./$@

$(testobjects): ; -@mkdir -p ./$@

$(objects): ; -@mkdir -p ./$@

