/******** DO NOT EDIT THIS FILE ********/
#ifndef _MUTEX_LOCKVAR_H
#define _MUTEX_LOCKVAR_H
#include "mutex.h"  // implemented by mutex_lockvar.c


/* 
 * Definition of mutex_lockvar_t - the underlying object that is stored
 * in shared memory and accessed by processes using the lock variable 
 * "solution" to mutual exclusion.
 * This approach does not solve the mutual exclusion problem.
 *
 * Type alias:
 * mutex_lockvar_t is a type alias for an unsigned short
 *
 * See also:
 * mutex_lockvar.c - for implementation of the mutex.h interface and
 *   the section on the lock variable busy waiting "solution" in CSC2035 
 *   lecture material on IPC
 */
typedef unsigned short mutex_lockvar_t;

#endif
