/******** DO NOT EDIT THIS FILE ********/
#ifndef _MUTEX_PETERSON_H
#define _MUTEX_PETERSON_H
#include "mutex.h"  // implemented by mutex_peterson.c

/* 
 * Definition of struct mutex_peterson - the Peterson mutex type that is stored
 * in shared memory and accessed by two processes using the Peterson solution
 * to mutual exclusion.
 *
 * Type alias:
 * A struct mutex_peterson can also be referred to as mutex_peterson_t
 *
 * Fields:
 * turn - the id of the process that has currently claimed the turn
 * interested - the array of indications of interest (for two processes)
 *
 * Note: for the purposes of the simulation and this implementation of 
 * Peterson's solution we assume that:
 *      1. process ids are positive (greater than or equal to 0)
 *      2. one of the two processes using this solution will have an even
 *          process id and the other will have an odd process id
 *
 * See also:
 * mutex_peterson.c - for implementation of the mutex.h interface and the 
 *      section on Peterson's busy waiting solution in CSC2035 lecture material
 *      on IPC
 */
typedef struct mutex_peterson {
    pid_t turn;
    int interested[2];
} mutex_peterson_t;

#endif
