/******** DO NOT EDIT THIS FILE ********/
#ifndef _MUTEX_NOOP_H
#define _MUTEX_NOOP_H
#include "mutex.h"  // implemented by mutex_noop.c


/* 
 * Definition of mutex_noop_t - the mutex type for the no-operation "solution"
 * to mutual exclusion. This solution is intended to demonstrate the effect
 * of no solution. That is, accessing shared data without mutual exclusion. 
 * Therefore, the mutex_enter and mutex_leave functions in mutex_noop.c
 * deliberately do nothing and permit unconstrained access to shared data for
 * multiple processes. This can be used to demonstrate that application
 * integrity will be violated if there is no control over access to critical
 * regions.
 *
 * Type alias:
 * mutex_noop_t is a type alias for an int
 *
 * See also:
 * mutex_noop.c - for implementation of the mutex.h interface
 */
typedef int mutex_noop_t;

#endif
