/******** DO NOT EDIT THIS FILE ********/
#include <stdlib.h>
#include "mutex_noop.h"
#include <errno.h>

/* mutex.h has the specification of functions in this file */

/* 
 * In the no operation version of a mutex, just allocate a 
 * mutex_noop_t object on the heap that is not shared between processes
 */
mutex_t* mutex_new(proc_t* proc) {
    if (!proc) {
        errno = EINVAL;
        return NULL;
    }

    return malloc(sizeof(mutex_noop_t));
}

/* 
 * This is a no operation version of mutex_enter - it deliberately does nothing
 */
void mutex_enter(mutex_t* mux) {
    return;
}

/* 
 * This is a no operation version of mutex_enter - it deliberately does nothing
 */
void mutex_leave(mutex_t* mux) {
    return;
}

/* 
 * This version of mu_delete just frees the memory allocated by mutex_new
 */
void mutex_delete(mutex_t* mux) {
    free(mux);
}
