#!/bin/bash
#******** DO NOT EDIT THIS FILE ********#
# This shell script is for running all tests in bin/test.
# Usage: 
#   ./runtests.sh [munit command line options]
# see: https://nemequ.github.io/munit/ for munit command line options

TEST_DIR=bin/test

for t in $TEST_DIR/test_*
do
    echo ------------------------------------------------------
    echo Running $t ...
    ./$t $*
    echo ------------------------------------------------------
done

