/******** DO NOT EDIT THIS FILE ********/
/* This is the semaphore producer application/simulation
 * Type:
 *      ./bin/sem_producer
 * for usage
 *
 * The source code for the usage message is in print_usage in sim_control.c.
 */
#include "sim_control.h"
#include "sem_jobqueue.h"

int main(int argc, char** argv) {
    shobj_ctrl_t queue_ctrl = { (sh_constructor_t) sem_jobqueue_new, 
        (sh_destructor_t) sem_jobqueue_delete };

    simulation_t* sim = simulation_setup(argc, argv, SEM_PROD_PROC,
        &queue_ctrl, NULL);
    
    proc_t* proc = sim->proc;
    
    unsigned int id = 1;
    
    while (proc->jobs) {
        job_t job;
        job_set(&job, proc->id, id, 1 + id % 3, 
            id % 2 ? "semodd_label" : "semeven_label");
        
        sem_jobqueue_enqueue(sim->queue, &job);  // waits until not full
        
        simulation_update(sim, &job);           // logs to the producer joblog

        id++;        
    }
    
    return simulation_teardown(sim);
}
