/******** DO NOT EDIT THIS FILE ********/
/* This is the semaphore consumer application/simulation
 * Type:
 *      ./bin/sem_consumer
 * for usage
 *
 * The source code for the usage message is in print_usage in sim_control.c.
 */
#include "sim_control.h"
#include "sem_jobqueue.h"

int main(int argc, char** argv) {
    shobj_ctrl_t queue_ctrl = { (sh_constructor_t) sem_jobqueue_new, 
        (sh_destructor_t) sem_jobqueue_delete };

    simulation_t* sim = simulation_setup(argc, argv, SEM_CONS_PROC,
        &queue_ctrl, NULL);
        
    proc_t* proc = sim->proc;

    while (proc->jobs) {
        job_t job;
        
        job_t* job_dq = sem_jobqueue_dequeue(sim->queue, &job);
            /* note: sem_jobqueue will be executed in a critical section 
             * and wait until the queue is not empty 
             * this is much simpler than the mutex version bwait_consumer
             */

        simulation_update(sim, job_dq); // logs to the consumer joblog
    }
    
    return simulation_teardown(sim);
}
