/******** DO NOT EDIT THIS FILE ********/
#include <stdlib.h>
#include <stdio.h>
#include "sim_config.h"
#include "shobject_name.h"

char* shobject_name(const char* label, char* name_buf) {
    label = label && label[0] ? label : "none";

    char* user = getenv("USER");
    
    if (!user) user = "anon";

    int r = name_buf 
            ? snprintf(name_buf, MAX_NAME_SIZE, SHOBJ_NAME_FMT, user, label)
            : asprintf(&name_buf, SHOBJ_NAME_FMT, user, label);

    return r < 0 ? NULL : name_buf;
}
