/******** DO NOT EDIT THIS FILE ********/
#ifndef _SIM_CONFIG_H
#define _SIM_CONFIG_H

#define MAX_NAME_SIZE 32 /* maximum bytes for a name - used for shared object
                          * names and job labels
                          */

#define MIN_WORK_DEFAULT 20
#define MAX_WORK_DEFAULT 40
#define DEFAULT_SKIP_FACTOR 1.0

/* JOB_LOG_PATH - the parent directory for logs */
#define JOBLOG_PATH "./out"

#endif