/******** DO NOT EDIT THIS FILE ********/
#ifndef _SIM_CTRL_H
#define _SIM_CTRL_H
#include "proc.h"
#include "job.h"

/*
 * pointers for shared object constructor and destructor function types
 */
typedef void* (*sh_constructor_t)(proc_t*);
typedef void (*sh_destructor_t)(void*); 

/* control of shared object construction and destruction */
typedef struct shobj_ctrl {
    sh_constructor_t constructor;
    sh_destructor_t destructor;
} shobj_ctrl_t;

/* information required to control a simulation */
typedef struct simulation {
    proc_t* proc;   
    void* queue;                            // the shared job queue
    sh_destructor_t queue_destructor;       // destructor for the queue
    void* mutex;                            // the busy waiting mute
    sh_destructor_t mutex_destructor;       // destructor for the mutex
    /* job control fields to detect skipped jobs during simulation */
    int skips;            
    int skip_limit;
} simulation_t;

/* setup a simulation from command line arguments */
simulation_t* simulation_setup(int argc, char** argv, proctype_t proc_type, 
    shobj_ctrl_t* queue_ctrl, shobj_ctrl_t* mutex_ctrl);

/* update simulation state during application execution */
void simulation_update(simulation_t* sim, job_t* job);
    
/* teardown a simulation printing summary information and removing resources */
int simulation_teardown(simulation_t* sim);

/* delete simulation resources (called as part of simulation_teardown) */
void simulation_delete(simulation_t* sim);

#endif